import React from "react";

const Home = () => {
    return (
        <>
            <div className="mobile_size">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe architecto itaque facere, excepturi explicabo corporis fuga accusantium deleniti. Totam in expedita iusto reprehenderit error eum cum ab natus. Ullam et at dicta tempore, quod omnis facilis maxime amet dolorem ipsum nulla vitae, placeat nisi expedita non minima! Est dignissimos facere at, ducimus amet aliquam tempore fuga voluptatibus laborum animi consequuntur hic officia perferendis incidunt laboriosam quis suscipit fugiat rem! Ad necessitatibus illum ullam blanditiis, aut enim nostrum fugit quibusdam ea dicta vitae quia iusto dolorum nihil? Temporibus ad amet eveniet incidunt. Fuga impedit tempora quas, obcaecati, cupiditate illum nisi, harum debitis adipisci accusamus velit. Facilis voluptas minus iste assumenda animi amet a consequuntur? Consectetur magni ducimus accusantium ut maxime ab, praesentium numquam blanditiis unde, sunt illo harum officiis cumque fugiat sit iure similique facilis quaerat. Aut hic maxime minus rerum explicabo, dolorum voluptates dolores odio officia libero. Voluptas incidunt iusto facere praesentium voluptatum magnam itaque magni maiores. Nam itaque recusandae animi pariatur? Vel eos molestias alias dolore perspiciatis delectus rerum omnis corrupti voluptate error magnam magni nisi, cupiditate expedita nobis. Veritatis officia debitis laudantium omnis. Ducimus deserunt consequuntur repellendus, ad dolor vel aperiam illum corrupti distinctio ratione consequatur quis deleniti temporibus rem delectus reiciendis dolores dolore qui nemo voluptates voluptatem adipisci perferendis repellat ea? Accusamus odio quis veniam eligendi quo ipsam cupiditate, obcaecati ducimus doloribus iusto praesentium aliquam quisquam debitis accusantium earum unde porro dolor nihil. Tenetur labore animi praesentium. Fugit soluta amet quis voluptas, temporibus nam unde blanditiis ex ea repellat esse, vero quam iusto enim. Amet aut deleniti dicta accusantium, saepe praesentium voluptas perferendis eligendi delectus natus eos velit. Maxime, eum. Eaque cumque quod veniam maiores dolores voluptatum, illum in inventore. Quis amet sequi rerum sit tempora ducimus tempore, nostrum distinctio, vero ad explicabo possimus qui! Illum odio quis vero veritatis repellendus ipsa vel eum alias ipsam illo, velit facilis nihil omnis praesentium et, quasi repellat consequatur eligendi harum voluptas, natus quod dolorem hic deleniti? Maiores soluta omnis magni quaerat distinctio, modi voluptas, laboriosam, rem ullam fugiat dolorum dicta facilis optio quasi qui repudiandae. Ex eius itaque quae excepturi aspernatur, deleniti ratione dolore aliquam voluptatum, molestiae suscipit tempora, dolor magni minima? Ex laudantium neque, dolor impedit molestias aliquam 
            </div>
        </>
    )
}

export default Home 